CREATE TABLE core.ads_fact (
  report_start_dt            TIMESTAMP,
  report_end_dt              TIMESTAMP,
  ad_id                      VARCHAR(50),
  ad_name                    VARCHAR(50),
  adset_id                   VARCHAR(50),
  adset_name                 VARCHAR(50),
  account_id                 VARCHAR(50),
  account_name               VARCHAR(50),
  campaign_id                VARCHAR(50),
  campaign_name              VARCHAR(50),
  age                        VARCHAR(50),
  gender                     VARCHAR(50),
  video_avg_time_watched     BIGINT,
  impressions                BIGINT,
  spend                      DECIMAL(18, 2),
  page_engagement_count      BIGINT,
  like_count                 BIGINT,
  post_engagement_count      BIGINT,
  post_share_count           BIGINT,
  comment_count              BIGINT,
  post_reaction_count        BIGINT,
  video_avg_percent_watched  DECIMAL(6, 2),
  outbound_clicks            BIGINT,
  unique_outbound_clicks     BIGINT,
  unique_clicks              BIGINT,
  link_clicks                BIGINT,
  unique_link_clicks         BIGINT,
  video_p25_watched_count    BIGINT,
  video_p50_watched_count    BIGINT,
  video_p75_watched_count    BIGINT,
  video_p95_watched_count    BIGINT,
  video_p100_watched_count   BIGINT,
  video_10_sec_watched_count BIGINT,
  video_30_sec_watched_count BIGINT,
  frequency                  DECIMAL(18, 7),
  reach                      BIGINT,
  social_impressions         BIGINT,
  social_reach               BIGINT,
  call_to_action_clicks      BIGINT,
  source_system              VARCHAR(45),
  cidw_etlload_id            INTEGER,
  cidw_load_dttm             TIMESTAMP DEFAULT getdate() NOT NULL ENCODE ZSTD
)
  DISTSTYLE EVEN
  SORTKEY (report_start_dt);
-- dist/sort key is temporary